import os

AUTH_JWT_SECRET_KEY = os.getenv("AUTH_JWT_SECRET_KEY")
AUTH_JWT_ALGORITHM = os.getenv("AUTH_JWT_ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("AUTH_ACCESS_TOKEN_EXPIRE_MINUTES"))
